Update Dockerfile

diff --git a/nut/Dockerfile b/nut/Dockerfile
--- a/nut/Dockerfile
+++ b/nut/Dockerfile
@@ -28,6 +28,7 @@ RUN \
 # hadolint ignore=DL3003
 RUN \
     mkdir -p /app /build \
+    && set -o pipefail \
     && cd /build \
     && NUT_FILENAME="nut-${NUT_VERSION}.tar.gz" \
     && NUT_DOWNLOAD_URL="https://github.com/networkupstools/nut/releases/download/v${NUT_VERSION}/${NUT_FILENAME}" \
@@ -40,7 +41,9 @@ RUN \
        --with-usb --with-hidapi --with-modbus --with-snmp --with-ssl --with-drivers=all \
     && make \
     && make DESTDIR=/app install \
-    && /app/usr/libexec/nut/nutdrv_hashx -h 2>&1 | grep -q "usb" || { echo "ERROR: nutdrv_hashx compiled without USB support"; exit 1; }
+    && if ! /app/usr/libexec/nut/nutdrv_hashx -h 2>&1 | grep -q "usb"; then \
+        echo "ERROR: nutdrv_hashx compiled without USB support"; exit 1; \
+    fi
 
 FROM base AS app
 
